### ISSUE TITLE
ImportError: cannot import name 'setup'

### ISSUE THREAD

**Issue by edongdongchen** [matteo-ronchetti/torch-radon#8] opened 2020-09-28 21:18 UTC
Hi Matteo,

Nice work! 
I encountered some error messages below when I tried to install your package from source. Do you know how to fix this?

Thanks,
Dongdong

---Steps:
$ git clone https://github.com/matteo-ronchetti/torch-radon.git
$ cd torch-radon
$ python setup.py install
---Errors:
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup
ImportError: cannot import name 'setup'

**Comment by matteo-ronchetti** [comment] 2020-09-29 10:42
Which version of python are you using?

**Comment by edongdongchen** [comment] 2020-09-29 10:46
The python version: 3.6.9

**Comment by matteo-ronchetti** [comment] 2020-09-29 10:49
Could you try installing setuptools with `pip install setuptools`?

**Comment by edongdongchen** [comment] 2020-09-29 10:54
I tried, but it doesn't work. It's weird

bash-4.2$ pip install setuptools
Requirement already satisfied: setuptools in /home/sys/anaconda3/envs/pytorch/lib/python3.6/site-packages (41.4.0)

**Comment by matteo-ronchetti** [comment] 2020-09-29 11:03
It's a very weird error I tried installing your version (41.4.0) of setuptools but I can't reproduce your issue. 

Could you please add the following code at the top of "setup.py"
```
import sys
print("Python version:", sys.version, sys.platform)
import setuptools
print("Setuptools version:", setuptools.__version__)
```
so that we could make sure that the python version running setup.py is correct

**Comment by edongdongchen** [comment] 2020-09-29 11:16
OK, please see below... still weird and no idea


bash-4.2$ python setup.py install
Python version: 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] linux
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    print("Setuptools version:", setuptools.__version__)
AttributeError: module 'setuptools' has no attribute '__version__'

**Comment by matteo-ronchetti** [comment] 2020-09-29 11:17
Could you try running `pip install --upgrade setuptools`?

**Comment by edongdongchen** [comment] 2020-09-29 11:23
bash-4.2$ pip install --upgrade setuptools
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/44/a6/7fb6e8b3f4a6051e72e4e2218889351f0ee484b9ee17e995f5ccff780300/setuptools-50.3.0-py3-none-any.whl (785kB)
     |████████████████████████████████| 788kB 3.2MB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 41.4.0
    Uninstalling setuptools-41.4.0:
      Successfully uninstalled setuptools-41.4.0
Successfully installed setuptools-50.3.0
bash-4.2$ python setup.py install
Python version: 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] linux
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    print("Setuptools version:", setuptools.__version__)
AttributeError: module 'setuptools' has no attribute '__version__'
bash-4.2$

**Comment by matteo-ronchetti** [comment] 2020-09-29 11:28
I'm confused but I think that pip is installing setuptools in a directory and setup.py is loading it from somewhere else.
Could you try putting `print("Setuptools version:", setuptools.__file__)`  instead of `print("Setuptools version:", setuptools.__version__)` so that we could check if it is loading the correct file

**Comment by edongdongchen** [comment] 2020-09-29 12:10
Yes pelase see below.

bash-4.2$ python setup.py install
Python version: 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] linux
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    print("Setuptools version:", setuptools.__file__)
AttributeError: module 'setuptools' has no attribute '__file__'

**Comment by matteo-ronchetti** [comment] 2020-09-29 12:27
I'm even more confused than before. Please try just `print("Setuptools:", setuptools)`

**Comment by edongdongchen** [comment] 2020-09-29 16:26
now it pops 'setuptools' is not defined

bash-4.2$ python setup.py install
Python version: 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] linux
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    print("Setuptools path:", inspect.getfile(setuptools))
NameError: name 'setuptools' is not defined

**Comment by edongdongchen** [comment] 2020-09-29 16:31
I just tried to install the package by using wget as you listed. But get the error said pytorch 1.3 was not supported. Can we play the package within pytorch 1.3 (we have to use this version for other dependencies)? 

wget -qO- https://raw.githubusercontent.com/matteo-ronchetti/torch-radon/master/auto_install.py  | python -

**Comment by matteo-ronchetti** [comment] 2020-09-29 19:43
> now it pops 'setuptools' is not defined
> 
> bash-4.2$ python setup.py install
> Python version: 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
> [GCC 7.3.0] linux
> Traceback (most recent call last):
> File "setup.py", line 4, in
> print("Setuptools path:", inspect.getfile(setuptools))
> NameError: name 'setuptools' is not defined

You need to put `import setuptools` before the print statement

**Comment by matteo-ronchetti** [comment] 2020-09-30 13:11
> I just tried to install the package by using wget as you listed. But get the error said pytorch 1.3 was not supported. Can we play the package within pytorch 1.3 (we have to use this version for other dependencies)?
> 
> wget -qO- https://raw.githubusercontent.com/matteo-ronchetti/torch-radon/master/auto_install.py | python -

I have added PyTorch 1.3 to the list of compilation targets. You should now be able to install TorchRadon using a precompiled package:
```
wget -qO- https://raw.githubusercontent.com/matteo-ronchetti/torch-radon/master/auto_install.py | python -
```

**Comment by matteo-ronchetti** [comment] 2020-10-06 13:51
@edongdongchen can you please update me?

**Comment by edongdongchen** [comment] 2020-10-09 00:11
Hi Matteo,
Sorry, I just tried again but got the below error, I am sure that my PyTorch had been updated to the latest version 1.6

bash-4.2$ wget -qO- https://raw.githubusercontent.com/matteo-ronchetti/torch-radon/master/auto_install.py | python -
Checking requirements
Operating System: linux OK
Python version: 3.6 OK
PyTorch: 0.4 ERROR
Precompiled packages are build for PyTorch 1.3, 1.4, 1.5 and 1.6
Consider manually compiling torch-radon

**Comment by matteo-ronchetti** [comment] 2020-10-09 17:10
Sorry but I think you have some problems with your python virtualenvs.
This is not an issue of the TorchRadon library, therefore I'm closing this issue.
If you need further help please contact me at my e-mail `mttronchetti@gmail.com`

**Closed by matteo-ronchetti** 2020-10-09 17:10 UTC

**Comment by edongdongchen** [comment] 2020-10-10 15:45
> Sorry but I think you have some problems with your python virtualenvs.
> This is not an issue of the TorchRadon library, therefore I'm closing this issue.
> If you need further help please contact me at my e-mail `mttronchetti@gmail.com`

Hi Matteo,

Happy to let you know that I'd solved the issues. It worked when I modified the '~/.bashrc' file. I have to alias the python version with another one that in my virtual env. Now it works smoothly. 

Thanks!
Dongdong
