### ISSUE TITLE
Error in Compilation

### ISSUE THREAD

**Issue by resonance20** [matteo-ronchetti/torch-radon#19] opened 2021-01-20 06:05 UTC
Output in shell:

(py3) C:\Users\z003zv1a\torch-radon>python setup.py install
Using CUDA_HOME=C:\CUDA\v10.1
[32mCompiling src\forward.template[0m
[34mC:\CUDA\v10.1/bin/nvcc -std=c++11 -ccbin=g++ -Xcompiler -fPIC -Xcompiler -static -Xcompiler -static-libgcc -Xcompiler -static-libstdc++ -I./include -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -DNDEBUG -O3 --generate-line-info --compiler-options -Wall -c src\forward.cu -o objs/cuda/forward.o[0m
ERROR IN COMPILATION

Operating system: Windows 10
Python version: 3.7

I see that Windows isn't supported oficially. Nevertheless, I'd appreciate any advice to address this issue.

**Comment by GEJansen** [comment] 2021-01-20 08:51
I was the one who opened the other issue on Windows support. I can only confirm I got the same error message on my windows machine. (Windows 10, CUDA v10.2, python 3.7)

**Comment by matteo-ronchetti** [comment] 2021-01-20 18:19
Currently Windows is not supported. The build script you are trying to run is written for Linux and therefore fails on Windows. I have zero knowledge of Windows and I can't port the compilation script to that OS.
I think that with good knowledge of Windows porting the build script shouldn't be hard.

This issue is a duplicate of https://github.com/matteo-ronchetti/torch-radon/issues/18 therefore I'm closing it.

**Closed by matteo-ronchetti** 2021-01-20 18:19 UTC
